module.exports = {
    content: ["./*.html"], plugins: [require("@tailwindcss/forms")], darkMode: "class",
    theme: {
      extend: {
        "colors": {
          "primary": "#000000",
          "surface-container-high": "#e8e8e8",
          "on-primary-fixed-variant": "#474746",
          "on-background": "#1a1c1c",
          "surface": "#f9f9f9",
          "secondary-fixed": "#ffe16d",
          "outline-variant": "#c4c7c7",
          "on-tertiary-container": "#868382",
          "primary-fixed": "#e5e2e1",
          "secondary-container": "#fcd400",
          "primary-fixed-dim": "#c8c6c5",
          "secondary-fixed-dim": "#e9c400",
          "surface-container-low": "#f3f3f3",
          "on-error": "#ffffff",
          "on-tertiary-fixed": "#1c1b1a",
          "tertiary-fixed-dim": "#cac6c4",
          "tertiary-container": "#1c1b1a",
          "tertiary": "#000000",
          "secondary": "#705d00",
          "surface-bright": "#f9f9f9",
          "on-error-container": "#93000a",
          "surface-variant": "#e2e2e2",
          "inverse-on-surface": "#f1f1f1",
          "surface-container-highest": "#e2e2e2",
          "surface-tint": "#5f5e5e",
          "on-surface-variant": "#444748",
          "error": "#ba1a1a",
          "inverse-primary": "#c8c6c5",
          "outline": "#747878",
          "surface-container-lowest": "#ffffff",
          "inverse-surface": "#2f3131",
          "primary-container": "#1c1b1b",
          "on-secondary-fixed": "#221b00",
          "tertiary-fixed": "#e6e2df",
          "background": "#f9f9f9",
          "on-primary-container": "#858383",
          "surface-container": "#eeeeee",
          "on-secondary": "#ffffff",
          "on-surface": "#1a1c1c",
          "on-tertiary": "#ffffff",
          "surface-dim": "#dadada",
          "on-secondary-container": "#6e5c00",
          "on-secondary-fixed-variant": "#544600",
          "on-primary-fixed": "#1c1b1b",
          "error-container": "#ffdad6",
          "on-tertiary-fixed-variant": "#484645",
          "on-primary": "#ffffff"
        },
        "borderRadius": {
          "DEFAULT": "30px",
          "lg": "30px",
          "xl": "30px",
          "full": "9999px"
        },
        "spacing": {
          "container-max": "1280px",
          "base": "8px",
          "gutter": "24px",
          "margin-mobile": "20px",
          "section-gap": "120px"
        },
        "fontFamily": {
          "headline-md": ["Inter"],
          "display-xl": ["Inter"],
          "body-lg": ["Inter"],
          "headline-lg-mobile": ["Inter"],
          "headline-lg": ["Inter"],
          "label-sm": ["Inter"],
          "body-md": ["Inter"]
        },
        "fontSize": {
          "headline-md": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
          "display-xl": ["96px", {"lineHeight": "1.0", "letterSpacing": "-0.04em", "fontWeight": "800"}],
          "body-lg": ["20px", {"lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400"}],
          "headline-lg-mobile": ["40px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
          "headline-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
          "label-sm": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700"}],
          "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
        }
      },
    },
  };